### PR TITLE
BUGZ-417 +BUGZ-431  White board controller refactor

### PR DESCRIPTION
**Pull request by MiladNazeri**
https://highfidelity.atlassian.net/browse/BUGZ-431
https://highfidelity.atlassian.net/browse/BUGZ-417

### CODE REVIEW

**Comment by qlipdahlin** [comment]
While using Vive VR, left hand laser would not activate to pick colors or reset the board. No laser appeared and pointing hand at correct location did not change anything either. Right hand did nothing either.

**Comment by salinacsoto** [comment]
It is very difficult to delete lines in desktop with the middle scroll button on my Windows PC

**Comment by salinacsoto** [comment]
hifi-snap-by-skelina-on-2019-06-07_14-25-25
I am able to pull lines out from the board on Master Build 10542. I tried using just simplified UI instead of having both and I still could repro. On my Macbook Air I could not repro.

**Comment by salinacsoto** [comment]
In the oculus rift s I am able to draw, erase and trigger the buttons on the whiteboard normally

**Comment by MiladNazeri** [comment]
Ooh, I hope the vive isn't different for some reason.  That's going to be a
hard one for me to check on with only an oculus system.

Peter, can you try the vive setup on the normal whiteboards and let me know
if they work as expected? That would be helpful to know.

**Pull request merged**
