### PR TITLE
Adding mirror to marketplace

### PR DESCRIPTION
**Pull request by PatrickManalich**
Finally adding the mirror to the marketplace! Woot!

# Test Plan
## Prerequisites
You should only need the latest dev download of [High Fidelity](https://highfidelity.com/dev-download)
## Tests

1. Turn on Advanced Menus by selecting "Settings -> Advanced Menus" on the menu bar.
2. Click "Edit -> Import Entities from URL" on the menu bar.
3. Copy and paste this link into the import field: https://raw.githubusercontent.com/patrickmanalich/hifi-content/hifi-content_mirror/Marketplace/mirror/m.json
4. Click "okay" and check to see if a mirror imports in front of you.
5. Check to see if a button has appeared near the top right corner of the mirror.
6. Check to see if a blue box has appeared at the lower right corner of the mirror.
7. Click the button with your mouse and ensure you see your avatar being rendered in the mirror, and that the button has changed to a red color.
8. Drag the blue box in multiple directions. See if the mirror stretches with the box, and the rendering stays aligned with the mirror. Also check that the box has a highlighted tint to it.
9. Let go of the blue box and make sure that box loses its highlighted tint and that the avatar is still being rendered.
10. Stretch the box as far and as small as you can, and make sure that the mirror has limits to how large and how small you can resize it.
11. Click the button with your mouse and ensure that you no longer see your avatar being rendered in the  mirror, and that the button has changed back to its grey color.
12. Go into HMD.
13. Laser trigger the button, and make sure that the mirror begins rendering (same as the mouse click).
14. Grab the blue box with you hand controller, and ensure that the dragging mechanism still works.
15. Laser trigger the button again, making sure the rendering stops.
16. Import the Spectator Camera from Marketplace and turn it on.
17. Attempt to turn on the mirror and make sure the mirror doesn't start rendering (it shouldn't turn on).
16. Delete the mirror and make sure both the button and the blue box are deleted with it.

### CODE REVIEW

**Comment by patrickmanalich** [comment]
@misslivirose so to do that I need to install ESLint and then what? How do I import hifi's coding style?

**Comment by misslivirose** [comment]
@patrickmanalich You can point the eslint configuration settings in your editor to the .eslintrc file at the root of this repository to apply the style checks

**Comment by Nex-Pro** [comment]
### FAIL

Turn on Advanced Menus by selecting "Settings -> Advanced Menus" on the menu bar.

Click "Edit -> Import Entities from URL" on the menu bar.

Copy and paste this link into the import field: https://raw.githubusercontent.com/patrickmanalich/hifi-content/hifi-content_mirror/Marketplace/mirror/m.json

Click "okay" and check to see if a mirror imports in front of you. **SUCCESS**

Check to see if a button has appeared near the top right corner of the mirror. **SUCCESS**

Check to see if a blue box has appeared at the lower right corner of the mirror. **SUCCESS**

Click the button with your mouse and ensure you see your avatar being rendered in the mirror, 
and that the button has changed to a red color. **SUCCESS**

Drag the blue box in multiple directions. See if the mirror stretches with the box, **SUCCESS** 
and the rendering stays aligned with the mirror. **SUCCESS** 
Also check that the box has a highlighted tint to it. **SUCCESS**

Let go of the blue box and make sure that box loses its highlighted tint and that the avatar is still being rendered. **SUCCESS**

Stretch the box as far and as small as you can, 
and make sure that the mirror has limits to how large and how small you can resize it. **FAIL** Several times while doing this there were problems.

**Mirror appeared as more than one component.**

**Blue box became invisible. ( should have been in view, could only be seen from certain angles )**

**Blue box can be moved below the floor and out of sight.**

**Blue box can scale the mirror to be wider by dragging beyond the left side of the mirror.**

**Blue box can be shift dragged vertically beyond the top edge of the mirror where it remains.**


Click the button with your mouse and ensure that you no longer see your avatar being rendered in the mirror,  **SUCCESS** 
and that the button has changed back to its grey color. **SUCCESS** 

Go into HMD.

Laser trigger the button, and make sure that the mirror begins rendering (same as the mouse click). **FAIL** Completely unreliable. Found that placing the hand very close to the button and triggering worked fine.

Grab the blue box with you hand controller, and ensure that the dragging mechanism still works. **PARTIAL SUCCESS** Works by grabbing, however if the box is hit by the laser it seems to become dynamic ( with damping ) and has no effect on the scale.

Laser trigger the button again, making sure the rendering stops. **FAIL** Unreliable as before.

Delete the mirror and make sure both the button and the blue box are deleted with it. **SUCCESS**

hifi-snap-by-piper-peppercorn-on-2017-11-05_07-11-56
hifi-snap-by-piper-peppercorn-on-2017-11-05_07-21-02

***Discovered a serious bug with importing ents from URL. Will confirm and post to fogbugz.***

**Comment by patrickmanalich** [comment]
I have believe I have fixed all the failed issues above, except for the "Stretch the box as far and as small as you can, and make sure that the mirror has limits to how large and how small you can resize it." Although this isn't the most graceful solution, it is the expected behavior. Should I push my changed code?

**Comment by PatrickManalich** [comment]
@misslivirose would you mind adding a QA ready label on this PR when you have a chance? I pushed a new commit.

**Comment by conklin94122** [comment]
@misslivirose Were your requested changes made? If not I'm going to remove QA Ready until they are.

**Comment by changxc** [comment]
I thought Patrick has responded to requested changes, or where they not sufficiently addressed?

**Comment by misslivirose** [comment]
The eslint changes do not appear to have been made, but shouldn't impact testing as they're all style-only

**Comment by changxc** [comment]
if the requested changes have been addressed (as seen in earlier comment), could we get some QA please? Thanks!

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Turn on Advanced Menus by selecting "Settings -> Advanced Menus" on the menu bar. **Check**
Click "Edit -> Import Entities from URL" on the menu bar. **Check**
Copy and paste this link into the import field: https://raw.githubusercontent.com/patrickmanalich/hifi-content/hifi-content_mirror/Marketplace/mirror/m.json **Check**
Click "okay" and check to see if a mirror imports in front of you. **Check**
Check to see if a button has appeared near the top right corner of the mirror. **Check**
Check to see if a blue box has appeared at the lower right corner of the mirror. **Check?.. Shows as gray until in use**
Click the button with your mouse and ensure you see your avatar being rendered in the mirror, and that the button has changed to a red color. **Check**
Drag the blue box in multiple directions. See if the mirror stretches with the box, and the rendering stays aligned with the mirror. Also check that the box has a highlighted tint to it. **Check**
Let go of the blue box and make sure that box loses its highlighted tint and that the avatar is still being rendered. **Check**
Stretch the box as far and as small as you can, and make sure that the mirror has limits to how large and how small you can resize it. **Check**
Click the button with your mouse and ensure that you no longer see your avatar being rendered in the mirror, and that the button has changed back to its grey color. **Check**
Go into HMD. **Check**
Laser trigger the button, and make sure that the mirror begins rendering (same as the mouse click). **Check**
Grab the blue box with you hand controller, and ensure that the dragging mechanism still works. **Check**
Laser trigger the button again, making sure the rendering stops. **Check**
Import the Spectator Camera from Marketplace and turn it on. **Check**
Attempt to turn on the mirror and make sure the mirror doesn't start rendering (it shouldn't turn on). **Check**
Delete the mirror and make sure both the button and the blue box are deleted with it. **Check**

Note: although it's not mentioned in test plan, if mirror is left on when using Spectator camera, the below occurs. (Mirror seems to copy spec-cam view but avatar is invisible)
image


Assuming the issue found outside of test plan does not warrant a fail, **Pass** @conklin94122

**Comment by changxc** [comment]
thank you~ 
@conklin94122 @misslivirose @themelissabrown

**Comment by changxc** [comment]
is anything blocking this to be submitted to marketplace? or should it submitted to caitlyn?

**Comment by misslivirose** [comment]
@changxc As I've mentioned, this isn't passing code review because the requested changes aren't being made.

**Comment by misslivirose** [comment]
@changxc It needs to be fixed before it gets a proper CR

**Comment by PatrickManalich** [comment]
I tried a couple times to install ESLint and check my code, but I was unable to get it working. Would someone with it already installed mind running it through and sending me the results so I can make the changes, or maybe help me install it so I can get a CR?

**Comment by PatrickManalich** [comment]
I'm not quite certain why when mirror is left on when using Spectator camera, the it seems to copy the spectator cam and show the user as invisible. There have may have been some changes in rendering that I am unaware of.

**Comment by misslivirose** [comment]
Closing given this was submitted to marketplace separately

**Pull request closed without merging**
