### PR TITLE
Some Flamethrower improvements!

### PR DESCRIPTION
**Pull request by zfox23**
Hi folks! A few improvements to the Flamethrower:
1. I don't know if this is kosher for this repo, but I added a `example_flamethrower.json` to the root of the `flamethrower` directory so that it's easier to spawn _a_ flamethrower (even if it doesn't have the most up-to-date URLs) if you just have the repo cloned.
2. Changed Flame texture to Rainbow texture
3. Improved throwing behavior by:
    - Initializing the same particle emitter upon script startup but initializing its `isEmitting` property to `false`
    - Turning the earlier-initialized emitter during `fire` and `stopFiring` - this way, it behaves more like a real flamethrower.

Check it out!

### CODE REVIEW

**Comment by dback2** [comment]
Original flame-based flamethrower moved to marketplace before these changes:
https://github.com/highfidelity/hifi-content/pull/133

**Comment by dback2** [comment]
Thanks for helping out on flamethrower @zfox23 !

**Comment by misslivirose** [comment]
I pulled down the repo and imported the flamethrower, but I'm not seeing any particle effects. Do I need to update the file references?

**Comment by misslivirose** [comment]
Tested internally, working great. Approved!

**Pull request merged**
