### PR TITLE
Parent Shapes UI to controllers instead of avatar hands

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- UI and controls are relative to user's physical hands.
- Handles changing dominant hand.
- Handles changing first/third person view.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
https://highfidelity.manuscript.com/f/cases/16563

**Comment by ctrlaltdavid** [comment]
# Test Plan

TESTING: Please test with the current, public release of High Fidelity.

KNOWN ISSUES:
* Line entity types are not supported.

## New Tests this Version

The UI is attached to your physical hands, not your avatar's hands:
* When wearing an avatar with short arms, the UI is positioned at the location of your physical hands.
* When in 3rd person view, the UI is positioned at the location of your physical hands. You can switch between first and third person views and the UI remains attached to your physical hands.
* You can change dominant hands and the UI remains attached to your physical hands.


## Running

* General test per User Guide.
* If you're in a domain where you don't have rez or rez-temp permissions and you try to turn the app on, an error beep is emitted when you press the button, a notification message is displayed, and the app UI does not appear on your hand.
* If the app is on and your domain stops or restarts, the app remains on (app UI disappears then reappears) though any current tool is dropped and it returns to the main menu.
* If your permissions are updated so that you no longer have rez or rez-temporary permissions, the UI closes if it is open and the app button is disabled.
* With editing active the following non-editing functions still work:
  * Laser and stylus on tablet UI and "x" button.
  * Grabbing and moving the tablet.
  * Teleporting using the controller teleport button.
* Test basics of operation (e.g., lasers) work when activate the app in desktop mode before entering HMD mode, and when activate app while in HMD mode.


### Grabbing

* General test per User Guide.
* Entity types that can be highlighted and grabbed:
  * Model
  * Shape (box, sphere, cylinder, etc.)
  * Text
  * Web
  * PolyLine
* Entity types that cannot be highlighted or grabbed:
  * Zone
  * Light
  * ParticleEffect
* Locked entities are highlighted but cannot be grabbed.
* Invisible entities are not highlighted and cannot be grabbed.

KNOWN ISSUES:
* Polylines cannot be laser-highlighted or laser-grabbed.


### Scale With Hands

* General test per User Guide.
* Test scaling entities and groups of entities with center and off-center registration points. Check rotations of children.


## Tools Menu

* General test per User Guide.
* Entity types that cannot be operated on:
  * Zone
  * Light
  * ParticleEffect


### Scale With Handles Tool

* General test per User Guide.
* Test scaling entities and groups of entities with center and off-center registration points. Check rotations of children.
* Test grabbing entities in different positions (e.g., center, one end, etc.).


### Clone Tool

* General test per User Guide.
* Test cloning entities with both hands simultaneously.


### Group/Ungroup Tool

* General test per User Guide.
* Test grouping and ungrouping several levels of groups.
* Test grouping and ungrouping different the entity types able to be highlighted per "Grabbing".


### Color Tool

* General test per User Guide.


### Physics Tool

* General test per User Guide.
* Test grouping and ungrouping entity sets with physics (gravity and collisions) applied.
  * When grouping, the resulting entity set has phycis if the parent selected has physics.
  * When ungrouping, if the entity set has physics then just resulting parent entity or group has physics and the detached children have default (i.e.) no physics.

POSSIBLE ISSUE: Some shapes other than box and sphere cannot be grabbed with controllerDispatcher.js. FB7333


### Delete Tool

* General test per User Guide.


### Undo, Redo

* General test per User Guide, for all app features.



## Create Palette

* General test per User Guide.
* Test creating entities while a tool is active. The entity should be created without the tool being applied (e.g., entity not colored, etc.).



## Miscellaneous Tests

* The UI is attached to your physical hands, not your avatar's hands.
  * When wearing an avatar with short arms, the UI is positioned at the location of your physical hands.
  * When in 3rd person view, the UI is positioned at the location of your physical hands. You can switch between first and third person views and the UI remains attached to your physical hands.
  * You can change dominant hands and the UI remains attached to your physical hands.
* You can use the tablet while the app is enabled.
* Test operations while you're inside an entity (e.g., inside a house model): you should be able to grab, create, color, etc., entities the same as if you're not inside an entity. Except that the entity you're inside is not highlighted unless you laser it or one of the entities in its linkset.
* When the app is running and you change your avatar, the UI closes. You can open it again by clicking the app icon.
* The UI is usable (readable) in low-light conditions, i.e., the necessary parts of the UI are bright.
* In your sandbox, unlock the builders grid and check that the UI still displays OK while you're standing on the grid.

**Comment by ctrlaltdavid** [comment]
# USER GUIDE


## Running

Running the script adds a "SHAPES" tablet/toolbar icon.

The icon is disabled if you start up not connected to a domain or teleport to a domain where you don't have rez or rez-temp permissions. However, once enabled it stays enabled if the domain stops, or if you teleport to a domain that isn't connected. (I.e., same behavior as edit.js's icon.)

Enable or disable editing by clicking the app icon to display a dialog that has a button that toggles the app on and off. The app can only be turned on if you're in a domain where you have rez or rez-temp permissions. The app is automatically turned off in you teleport to a domain where you don't have rez or rez-temp permissions.

When the app is on, the app icon is highlighted and a "Tools" menu and "Create" palette are attached to your non-dominant hand. (Use Settings > Avatar > Dominant Hand to set your dominant hand.)

The UI is hidden if your hand is at or inside an entity but your viewpoint is outside it.


### Grabbing

* This is the default action for each hand with no tool active (i.e., no tool icon on your non-dominant hand).
* Make your hand or blue laser (partially squeezed trigger) intersect an entity. All the entities in that entity's parent/child tree are highlighted in yellow.
* Fully squeeze the trigger to grab the set of entities. The entities stop being highlighted and start translating and rotating 1-1 with your hand translation and rotation.
* You can grab and manipulate two sets of entities simultaneously: one with each hand/laser.
* To delete the grabbed entities, press the grip trigger/button on the controller that's grabbing them. This is an alternative to using the Delete tool.
* The following entity types cannot be grabbed: light, particle effect, and zone.

NOTE: Entities are only highlighted if visible and grabbable if the root of the tree is not locked, and not a zone, light, or particle effect.


### Scale With Hands

* This is the default action when using both hands on the same entity or set of entities.
* Make your second hand/laser intersect an entity in the set you have grabbed with your first hand. All the entities in the set are highlighted in cyan.
* Fully squeeze your second hand's trigger. The entities stop being highlighted and start being scaled and rotated as you move your hands.
* If you let go with one hand, the entities continue to be grabbed by the hand still grabbing them.


## Tools Menu

* To activate a tool, click on its button. An icon representing it is attached to your dominant hand.
* To deactivate a tool, hover the title bar so that it displays "Back" and click it, or click a grip trigger/button on a hand that you're not grabbing entities with. (See also, the Delete tool.)
* The following entity types cannot be operated on: light, particle effect, and zone.


### Scale With Handles Tool

* Make your hand or blue laser (partially squeezed trigger) intersect an entity. All the entities in that entity's parent/child tree are highlighted in cyan - to indicate "about to scale".
* Fully squeeze the trigger to grab the set of entities. Scale handles are displayed and the entities start translating and rotating 1-1 with your hand translation and rotation.
* Grab a handle with your second hand / laser and move it. The entity is scaled in that axis if a face handle, or as a whole if a corner handle.
* Face handles are not displayed if multiple entities are selected. (Some may be at an angle relative to the root entity which would necessitate a shear transform - not available in Interface - be applied to them when scaling a face of the set.)
* Z-axis handles are not displayed if scaling a text or Web entity.


### Clone Tool

* Make your hand or blue laser (partially squeezed trigger) intersect an entity. 
* Fully squeeze the trigger to clone the set of entities and then start grabbing it.


### Group/Ungroup Tool

* Select one or more sets of entities by clicking on them. Selected entities are highlighted in magenta.
* Green "Group" button: Press this button to group the entities selected in a parent-child relationship. The first entity or entity selected is used as the parent. (Button is enabled only if two or more sets of entities are selected.)
* Red "Ungroup" button: Press this button to ungroup the enttiy set selected. (Button is enabled only if one entity set with two or more entities is selected.)
* "Select in box" dotted rectangle button: When this is toggled on, a bounding box emcompassing your selected items is drawn and all entity sets contained within this box are automatically selected. The orientation of the bounding box is per the orientation of first entity in the first entity set selected.
* "Clear" button: Deselects all entities.
* Grouping and ungrouping is relative to the root entity of the first entity set selected.
* You can group and ungroup more than one level of parent-child relationships.


### Color Tool

* Click on and drag your laser beam in the color circle and slider to change the color in the "current color" patch.
* Click on an entity to apply the color in the "current color" patch to that entity.
* For entity sets, only the intersected entity is highlighted and the color is applied to only that entity.
* Only shape (box, sphere, cylinder, etc.) and polyline entity types can be colored.
* There are several color swatches, empty by default.
* Trigger-click an empty color swatch to set its color to the current color. 
* Grip-click a filled color swatch to clear it to empty. 
* Color swatches persist across Interface runs.
* Click the "Pick" button to change into "pick color" mode, then click on an entity to pick that entity's color as the current color. You can pick colors from both unlocked and locked entities.


The following entity types do not take color:
* Model.
* Web.
* Text.


### Physics Tool

* Adjust the settings in the options panel then click on an entity to apply them to that entity or entity set. 
* Physics settings persist across Interface runs.

The following entity types do not take gravity:
* Web.
* Text.

NOTE: With entity sets, the physics is applied to the root entity and child entities' properties are adjusted as necessary to make physics work within High Fidelity's current limitations w.r.t. physics and entity sets.
NOTE: With entity sets, only the root entity collides with other entities (a current limitation of High Fidelity).


### Delete Tool

* Make your hand or blue laser (partially squeezed trigger) intersect an entity. 
* Fully squeeze the trigger to delete the entity or set of entities.
* Alternatively, you can delete entities without using this tool by grabbing them and clicking the grip trigger/button.


### Undo, Redo

* Press the undo button one or more times to undo your latest edits.
* After undoing some edits, you can redo them by pressing the redo button.
* If you undo some edits then make a new edit, the new edits that you undo are forgotten (i.e., the new edit replaces them in your edit history).
* There's an error beep if there's nothing to undo or redo when you press the button.



## Create Palette

* Click an entity represented in the palette and the entity will be created at your hand.
* If you continue to hold the trigger pressed the entity is automatically grabbed.

**Comment by misslivirose** [comment]
Approving per marketplace QA and approval

**Pull request merged**
