### PR TITLE
fix variable names in spawnAttachmentRemovalZone

### PR DESCRIPTION
**Pull request by misslivirose**

### CODE REVIEW

**Comment by misslivirose** [comment]
Test plan: 
Run https://raw.githubusercontent.com/misslivirose/hifi-content/83290828ff123342fce7293ce018c4739be2c95f/DomainContent/AvatarStore/AttachmentRemovalZone/spawnAttachmentRemovalZone.js and make sure the zone spawns

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Pass** :)

image

**Comment by misslivirose** [comment]
Thanks @YuppyPlays!

**Pull request merged**
