### PR TITLE
Attachment shelve (local avatar entities)

### PR DESCRIPTION
**Pull request by thoys**
Attachments can now be grabbed without the need of rez-permissions.

### CODE REVIEW

**Comment by thoys** [comment]
Removed the ESS way of creation as that was not very reliable. Moved to avatar entities. Feels way better.

**Comment by misslivirose** [comment]
Is this live in dev-content to test?

**Comment by thoys** [comment]
that is correct @misslivirose

**Comment by misslivirose** [comment]
Looks good to me - QA Pass

**Pull request merged**
