### PR TITLE
Sword Battle Game

### PR DESCRIPTION
**Pull request by jfcarter**
This is a two person game and as such requires at least two testers. One person needs to create the arena through the tablet app (instructions below). If you can test with at least one bystander that would be great. Please test this game using the knight avatar https://hifi-content.s3.amazonaws.com/jedon/Game_Creater_Toolkit/ROC/SwordGameAvatars/fst/warrior_Rigged.fst

1. Click Edit -> Open and run script from URL -> then enter this link to add the app to your tablet
https://hifi-content.s3.amazonaws.com/jedon/Game_Creater_Toolkit/VS/VS_Arena_Creator.js
2. Download VS app through file VS_Arena_Creator.js (app named "VS" with a sword icon)(Icon will be replaced later)
3. open VS app and see two buttons. "Place Arena" and "Clear Arena".
4. Click place arena and you will see an arena placed in front of you with a sign to its left, two knights to its right, a sign above the two knights, and two sets of sword and rock entites placed at both ends of arena. 
5. Switch to HMD mode
6. Pick up sword and you will hear a "swish" sound followed by an alert that the game is equipping your armor. You will be equipped with invisible armor, health indicator, and a shield after you hear "armor equipped". NOTE: Please stand still during equip times.
7. Your shield should equip to you. If not then grab it (sometimes does not equip if you move during equip speech)
8. When you are hit you will lose one of the hearts floating above your head as well as one of the hearts on your shield. You should also hear me say the word "Hit".
9. When you are blocked your sword will turn red and you will experience some haptic feedback. Your sword is then disabled for 1 second (you can no longer deal damage to your enemy during that time). You will also hear me say the word blocked
10. Hit the Reset sign with your hand laser to reset the game at any point. You will feel haptic feedback when you do.
11. At the end of each game the winners sword will be replaced with a trophy while the losers sword will be replaced with a rubber chicken
12. When you press the sign above the knights it will open your tablet to the marketplace section where you can equip the knight.
13. Please let me know if you experience any lag. As well as when such lag happened.

### CODE REVIEW

**Comment by ShoaibSmith** [comment]
Is there a build for this?

**Comment by ShoaibSmith** [comment]
Testing

**Comment by ShoaibSmith** [comment]
Fail - Tested on release build 7071

Click Edit -> Open and run script from URL -> then enter this link to add the app to your tablet 
https://hifi-content.s3.amazonaws.com/jedon/Game_Creater_Toolkit/ROC/ROC_Arena_Creator.js
Download ROC app through file ROC_Arena_Creator.js (app named "ROC" with a sword icon)(Icon will be replaced later)
**Pass**
open Roc app and see two buttons. "Place Arena" and "Clear Arena". **Pass**
Click place arena and you will see an arena placed in front of you with a sign to its left, two knights to its right, a sign above the two knights, and two sets of sword and rock entites placed at both ends of arena. (sign has texture issue which will be fixed soon) **Check**
Switch to HMD mode **Pass**
Pick up sword and you will hear a "swish" sound followed by an alert that the game is equipping your armor. You will be equipped with invisible armor, health indicator, and a shield after you hear "armor equipped". **Pass**
Grab your shield and begin to battle. **Pass**
When you are hit you will lose one of the hearts floating above your head as well as one of the hearts on your shield. You should also hear me say the word "Hit". ****Fail** There is no collision between the two avatars.** 
When you are blocked your sword will turn red and you will experience some haptic feedback. Your sword is then disabled for 3 second (you can no longer deal damage to your enemy). You will also hear me say the word blocked **Pass**
Hit the Reset sign with your hand laser to reset the game at any point. You will feel haptic feedback when you do. **Pass**
At the end of each game the winners sword will be replaced with a trophy while the losers sword will be replaced with a rubber chicken ****Fail** Due to the fact that we could not fight.** 
When you press the sign above the knights it will open your tablet to the marketplace section where you can equip the knight. **Pass**

**Comment by Nex-Pro** [comment]
### FAIL on several points.

Click Edit -> Open and run script from URL -> then enter this link to add the app to your tablet

https://hifi-content.s3.amazonaws.com/jedon/Game_Creater_Toolkit/VS/VS_Arena_Creator.js

Download VS app through file VS_Arena_Creator.js (app named "VS" with a sword icon)(Icon will be replaced later)

open VS app and see two buttons. "Place Arena" and "Clear Arena".

Click place arena and you will see an arena placed in front of you with a sign to its left **SUCCESS**, 
two knights to its right **SUCCESS**,
a sign above the two knights **SUCCESS,
and two sets of sword and rock entites placed at both ends of arena. **SUCCESS**

All entities appeared but Knights had feet in the groundplane.the reset sign was partly in the ground.

Switch to HMD mode

Pick up sword and you will hear a "swish" sound **SUCCESS** However sound doesn't always come from where the sword is.

followed by an alert that the game is equipping your armor **Neither of us noticed the alert over several tries**. 

You will be equipped with invisible armor, health indicator, and a shield after you hear "armor equipped". **FAIL** Saw none of these at high fidelity's sandbox domain. Only the User running the domain on localhost gets the "Armour equipped" Message. we tried this on a total of three domains.

NOTE: Please stand still during equip times.

Your shield should equip to you. **Saw shield equip to avatar once in more than 20 attempts.** If not then grab it (sometimes does not equip if you move during equip speech) **Mostly does not equip even if standing still** 

**Unable to proceed past this point as we never managed to get both avatars equipped**

When you are hit you will lose one of the hearts floating above your head as well as one of the hearts on your shield. You should also hear me say the word "Hit". **UNABLE TO TEST**

When you are blocked your sword will turn red and you will experience some haptic feedback. Your sword is then disabled for 1 second (you can no longer deal damage to your enemy during that time). You will also hear me say the word blocked **UNABLE TO TEST**


Hit the Reset sign with your hand laser to reset the game at any point. You will feel haptic feedback when you do. **As we never managed to get the game started could not check this.**

At the end of each game the winners sword will be replaced with a trophy while the losers sword will be replaced with a rubber chicken **UNABLE TO TEST**


When you press the sign above the knights it will open your tablet to the marketplace section where you can equip the knight. **SUCCESS**

Please let me know if you experience any lag. As well as when such lag happened.

**NOTES:**

In the two domains we tested other than hifi sandbox we both had full perms.

Hearts and shields are not deleted if the arena is cleared before the game is started.

When my fight partner clicked the 'place arena' button or 'Clear arena' button her avatar changed back to the default wooden mannequin.

 Hearts above equipped avatar's head are aligned at some angle other than straight across.

 The equipping message sound each avatar is supposed to hear should be made local to that avatar.

 When my fight partner drew the sword in her domain I saw it remain in the stone she saw it in her hand.

**Comment by misslivirose** [comment]
@jfcarter is this ready to be QA tested again?

**Pull request closed without merging**
