### PR TITLE
Pinata and Cemetery Candle Filters (plus other minor changes in Mexico)

### PR DESCRIPTION
**Pull request by elisa-lj11**
## Test Plan
1. Log out of your hifi account
2. Go to hifi://mexico/500.264,498.531,506.531/0,0.999461,0,-0.0328275
3. Try to delete one of the fire particle entities (the candle) - it shouldn't disappear
5. Walk into the cemetery and let the floating spirit into you (you may need to step forward into the spirit if it's floating inside of you)
6. It should turn into a marigold and you should hear a harp sound
7. Go to hifi://mexico/540.454,499.379,493.112/0,-0.686987,0,0.72667
8. Try to delete the pinata, the bat, and the pinata pole - they shouldn't disappear

### Manuscript Cases
- https://highfidelity.fogbugz.com/f/cases/14683/Add-pinata-to-hifi-mexico-village-add-delete-filter
- https://highfidelity.fogbugz.com/f/cases/14681/Replace-candles-in-hifi-mexico-cemetery-add-delete-filter

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
**Testing complete:**
Log out of your hifi account **Check**
Go to hifi://mexico/500.264,498.531,506.531/0,0.999461,0,-0.0328275 **Check**
Try to delete one of the fire particle entities (the candle) - it shouldn't disappear **Check**
Walk into the cemetery and let the floating spirit into you (you may need to step forward into the spirit if it's floating inside of you) **Check**
It should turn into a marigold and you should hear a harp sound **Check**
Go to hifi://mexico/540.454,499.379,493.112/0,-0.686987,0,0.72667 **Check**
Try to delete the pinata, the bat, and the pinata pole - they shouldn't disappear **Couldn't find the bat in its usual place, everything else is a Check though.**

**Notes:** I could manipulate position & size still on the tested objects, however delete I could not.

Not sure if Pass/Fail, everything but the Bat worked. I'd assume **Pass**

**Comment by misslivirose** [comment]
@elisa-lj11 can you check on the status of the bat in Mexico?

**Comment by elisa-lj11** [comment]
The issue with the bat is not the delete filters; I have a client script set on the bat so it stops working when I leave the domain. The delete filters work properly, but I need to update the pinata scripts themselves.

**Pull request closed without merging**
